apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-anll
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-anll
    app.kubernetes.io/part-of: cin4s-839-0070-app
  name: devfile-sample-anll
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-anll
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-anll
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0070-tenant/cin4s-839-0070-app/devfile-sample-anll@sha256:37a96f4220b9d2e336f2e47c912123759b263d398417f2ab2c31602d1876dd8d
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
